# Generated by Django 5.0.3 on 2024-03-29 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HellowWorld',
            new_name='HelloWorld',
        ),
    ]
